spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost
    username: admin
    password:

weather:
  api:
    url: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}
    appid: b7eb5291813efb2956fe2e1c14a933f9

logging:
  level:
    org:
      springframework=DEBUG